models/Cars.php
<?php

namespace app\models;

use Yii;
use yii\helpers\Html;

/**
 * This is the model class for table "cars".
 *
 * @property int $id
 * @property int $api_id
 * @property string $lu
 * @property int $old_price
 * @property int $company_id
 * @property int $cid
 * @property int $eigandi
 * @property int $flokkur
 * @property int $argerd
 * @property int $dyr
 * @property int $manna
 * @property int $ekinn
 * @property int $litur
 * @property int $drif
 * @property int $girar
 * @property int $eldsneyti
 * @property int $sumardekk
 * @property int $vetrardekk
 * @property int $heilsarsdekk
 * @property int $lowprofiledekk
 * @property int $slagrymi
 * @property string $aukahlutirath
 * @property int $skiptiodyrari
 * @property int $skiptiodyrarikr
 * @property int $skiptidyrari
 * @property int $skiptidyrarikr
 * @property string $skiptiath
 * @property int $naestaskodun
 * @property string $skrdags
 * @property int $verd
 * @property int $bilalan
 * @property int $bilalanupphaed
 * @property int $lanveitandiid
 * @property int $bilalanafborgun
 * @property int $dekkjastaerd
 * @property int $hestofl
 * @property int $afkostmaxkw
 * @property int $strokkar
 * @property int $tyngd
 * @property string $fyrstiskrdagur
 * @property int $spot
 * @property string $verdath
 * @property int $verdtilbod
 * @property int $skrmanudur
 * @property int $modelar
 * @property string $lastupdated
 * @property string $aukahlutir
 * @property int $akeiningar
 * @property int $bilalanlokagreidsla
 * @property int $bilalanlanstimi
 * @property int $burdargeta
 * @property int $tjonabifreid
 * @property string $stadsetning
 * @property int $nytt
 * @property int $innflteg
 * @property int $felgustaerd
 * @property int $spennarafkerfis
 * @property int $eftirafdekkjum
 * @property int $oxlafjoldi
 * @property int $nytimareim
 * @property int $timareimkm
 * @property int $anvsk
 * @property int $stadsettpnr
 * @property int $flokkur2
 * @property int $flokkur3
 * @property int $eldsneyti2
 * @property double $eydslainnanb
 * @property double $eydslautanb
 * @property double $eydslablandad
 * @property int $co2
 * @property int $skrath
 * @property int $fjlykla
 * @property int $fjlyklaremote
 * @property int $timabunadur
 * @property int $girartegund
 * @property int $solulysing
 * @property int $thskodun
 * @property int $thskodunkm
 * @property int $thskodundags
 * @property double $batterykw
 * @property int $batterykm
 * @property int $verdadurkr
 * @property int $ext_imagecount
 * @property string $ext_modframleidandi
 * @property int $ext_modframleidandiid
 * @property string $ext_modgerd
 * @property int $ext_modgerdid
 * @property int $ext_ekinnkm
 * @property int $ext_argerd
 * @property int $ext_statid
 * @property int $ext_sortkey
 * @property int $deleted
 * @property int $deleted_at
 * @property int $main_img
 * @property string $created
 * @property string $updated
 *
 * @property Companies $company
 * @property Eldsneyti $eldsneyti0
 * @property Eldsneyti $eldsneyti20
 * @property Flokkar $flokkur0
 * @property Framleidendur $extModframleidandi
 * @property Girartegund $girartegund0
 * @property Litir $litur0
 * @property CarsContactForm[] $carsContactForms
 * @property CarsFavorite[] $carsFavorites
 * @property CarsPhoto[] $carsPhotos
 * @property CarsProps[] $carsProps
 * @property CarsView[] $carsViews
 */
class Cars extends \app\models\BaseModel
{
    public $title;
    public $oldPrice;

    public $model_name;
    public $discount_price;
    public $on_website;
    public $page_views;
    public $in_search;
    public $contact_clicks;
    public $alerts;

    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'cars';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['api_id'], 'required'],
            [['api_id', 'old_price', 'company_id', 'cid', 'eigandi', 'flokkur', 'argerd', 'dyr', 'manna', 'ekinn', 'litur', 'drif', 'girar', 'eldsneyti', 'sumardekk', 'vetrardekk', 'heilsarsdekk', 'lowprofiledekk', 'slagrymi', 'skiptiodyrari', 'skiptiodyrarikr', 'skiptidyrari', 'skiptidyrarikr', 'naestaskodun', 'verd', 'bilalan', 'bilalanupphaed', 'lanveitandiid', 'bilalanafborgun', 'dekkjastaerd', 'hestofl', 'afkostmaxkw', 'strokkar', 'tyngd', 'spot', 'verdtilbod', 'skrmanudur', 'modelar', 'akeiningar', 'bilalanlokagreidsla', 'bilalanlanstimi', 'burdargeta', 'tjonabifreid', 'nytt', 'innflteg', 'felgustaerd', 'spennarafkerfis', 'eftirafdekkjum', 'oxlafjoldi', 'nytimareim', 'timareimkm', 'anvsk', 'stadsettpnr', 'flokkur2', 'flokkur3', 'eldsneyti2', 'co2', 'skrath', 'fjlykla', 'fjlyklaremote', 'timabunadur', 'girartegund', 'solulysing', 'thskodun', 'thskodunkm', 'thskodundags', 'batterykm', 'verdadurkr', 'ext_imagecount', 'ext_modframleidandiid', 'ext_modgerdid', 'ext_ekinnkm', 'ext_argerd', 'ext_statid', 'ext_sortkey', 'deleted', 'deleted_at', 'main_img'], 'integer'],
            [['lu', 'lastupdated', 'created', 'updated'], 'safe'],
            [['aukahlutirath', 'verdath'], 'string'],
            [['eydslainnanb', 'eydslautanb', 'eydslablandad', 'batterykw'], 'number'],
            [['skiptiath', 'skrdags', 'fyrstiskrdagur', 'stadsetning', 'ext_modframleidandi', 'ext_modgerd'], 'string', 'max' => 50],
            [['aukahlutir'], 'string', 'max' => 600],
            [['company_id'], 'exist', 'skipOnError' => true, 'targetClass' => Companies::className(), 'targetAttribute' => ['company_id' => 'id']],
            [['eldsneyti'], 'exist', 'skipOnError' => true, 'targetClass' => Eldsneyti::className(), 'targetAttribute' => ['eldsneyti' => 'id']],
            [['eldsneyti2'], 'exist', 'skipOnError' => true, 'targetClass' => Eldsneyti::className(), 'targetAttribute' => ['eldsneyti2' => 'id']],
            [['flokkur'], 'exist', 'skipOnError' => true, 'targetClass' => Flokkar::className(), 'targetAttribute' => ['flokkur' => 'id']],
            [['ext_modframleidandiid'], 'exist', 'skipOnError' => true, 'targetClass' => Framleidendur::className(), 'targetAttribute' => ['ext_modframleidandiid' => 'id']],
            [['girartegund'], 'exist', 'skipOnError' => true, 'targetClass' => Girartegund::className(), 'targetAttribute' => ['girartegund' => 'id']],
            [['litur'], 'exist', 'skipOnError' => true, 'targetClass' => Litir::className(), 'targetAttribute' => ['litur' => 'id']],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('app', 'ID'),
            'api_id' => Yii::t('app', 'Api ID'),
            'lu' => Yii::t('app', 'Lu'),
            'old_price' => Yii::t('app', 'Old Price'),
            'company_id' => Yii::t('app', 'Company ID'),
            'cid' => Yii::t('app', 'Cid'),
            'eigandi' => Yii::t('app', 'Eigandi'),
            'flokkur' => Yii::t('app', 'Flokkur'),
            'argerd' => Yii::t('app', 'Argerd'),
            'dyr' => Yii::t('app', 'Dyr'),
            'manna' => Yii::t('app', 'Manna'),
            'ekinn' => Yii::t('app', 'Ekinn'),
            'litur' => Yii::t('app', 'Litur'),
            'drif' => Yii::t('app', 'Drif'),
            'girar' => Yii::t('app', 'Girar'),
            'eldsneyti' => Yii::t('app', 'Eldsneyti'),
            'sumardekk' => Yii::t('app', 'Sumardekk'),
            'vetrardekk' => Yii::t('app', 'Vetrardekk'),
            'heilsarsdekk' => Yii::t('app', 'Heilsarsdekk'),
            'lowprofiledekk' => Yii::t('app', 'Lowprofiledekk'),
            'slagrymi' => Yii::t('app', 'Slagrymi'),
            'aukahlutirath' => Yii::t('app', 'Aukahlutirath'),
            'skiptiodyrari' => Yii::t('app', 'Skiptiodyrari'),
            'skiptiodyrarikr' => Yii::t('app', 'Skiptiodyrarikr'),
            'skiptidyrari' => Yii::t('app', 'Skiptidyrari'),
            'skiptidyrarikr' => Yii::t('app', 'Skiptidyrarikr'),
            'skiptiath' => Yii::t('app', 'Skiptiath'),
            'naestaskodun' => Yii::t('app', 'Naestaskodun'),
            'skrdags' => Yii::t('app', 'Skrdags'),
            'verd' => Yii::t('app', 'Verd'),
            'bilalan' => Yii::t('app', 'Bilalan'),
            'bilalanupphaed' => Yii::t('app', 'Bilalanupphaed'),
            'lanveitandiid' => Yii::t('app', 'Lanveitandiid'),
            'bilalanafborgun' => Yii::t('app', 'Bilalanafborgun'),
            'dekkjastaerd' => Yii::t('app', 'Dekkjastaerd'),
            'hestofl' => Yii::t('app', 'Hestofl'),
            'afkostmaxkw' => Yii::t('app', 'Afkostmaxkw'),
            'strokkar' => Yii::t('app', 'Strokkar'),
            'tyngd' => Yii::t('app', 'Tyngd'),
            'fyrstiskrdagur' => Yii::t('app', 'Fyrstiskrdagur'),
            'spot' => Yii::t('app', 'Spot'),
            'verdath' => Yii::t('app', 'Verdath'),
            'verdtilbod' => Yii::t('app', 'Verdtilbod'),
            'skrmanudur' => Yii::t('app', 'Skrmanudur'),
            'modelar' => Yii::t('app', 'Modelar'),
            'lastupdated' => Yii::t('app', 'Lastupdated'),
            'aukahlutir' => Yii::t('app', 'Aukahlutir'),
            'akeiningar' => Yii::t('app', 'Akeiningar'),
            'bilalanlokagreidsla' => Yii::t('app', 'Bilalanlokagreidsla'),
            'bilalanlanstimi' => Yii::t('app', 'Bilalanlanstimi'),
            'burdargeta' => Yii::t('app', 'Burdargeta'),
            'tjonabifreid' => Yii::t('app', 'Tjonabifreid'),
            'stadsetning' => Yii::t('app', 'Stadsetning'),
            'nytt' => Yii::t('app', 'Nytt'),
            'innflteg' => Yii::t('app', 'Innflteg'),
            'felgustaerd' => Yii::t('app', 'Felgustaerd'),
            'spennarafkerfis' => Yii::t('app', 'Spennarafkerfis'),
            'eftirafdekkjum' => Yii::t('app', 'Eftirafdekkjum'),
            'oxlafjoldi' => Yii::t('app', 'Oxlafjoldi'),
            'nytimareim' => Yii::t('app', 'Nytimareim'),
            'timareimkm' => Yii::t('app', 'Timareimkm'),
            'anvsk' => Yii::t('app', 'Anvsk'),
            'stadsettpnr' => Yii::t('app', 'Stadsettpnr'),

models/CarsView.php
<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "cars_view".
 *
 * @property int $id
 * @property int $key_id
 * @property int $car_id
 * @property string $created
 *
 * @property CarsViewKey $key
 * @property Cars $car
 */
class CarsView extends \app\models\BaseModel
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'cars_view';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['key_id', 'car_id'], 'integer'],
            [['created'], 'safe'],
            [['key_id'], 'exist', 'skipOnError' => true, 'targetClass' => CarsViewKey::className(), 'targetAttribute' => ['key_id' => 'id']],
            [['car_id'], 'exist', 'skipOnError' => true, 'targetClass' => Cars::className(), 'targetAttribute' => ['car_id' => 'id']],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('user', 'ID'),
            'key_id' => Yii::t('user', 'Key ID'),
            'car_id' => Yii::t('user', 'Car ID'),
            'created' => Yii::t('user', 'Created'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getKey()
    {
        return $this->hasOne(CarsViewKey::className(), ['id' => 'key_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCar()
    {
        return $this->hasOne(Cars::className(), ['id' => 'car_id']);
    }

    public static function setView($car)
    {
        $key = Yii::$app->session->get('view_key');
        $car_view_key = CarsViewKey::find()->where(['key' => $key])->one();
        if (!$car_view_key) {
            $car_view_key = new CarsViewKey();
            $car_view_key->key = self::generateRandomString(50);
            $car_view_key->ip = Yii::$app->getRequest()->getUserIP();

            $headers = Yii::$app->request->headers;
            if ($headers->has('User-Agent')) {
                $car_view_key->user_agent = $headers->get('User-Agent');
            }


            if (!$car_view_key->save()) {
                print_r($car_view_key->getErrors());
            } else {
                Yii::$app->session->set('view_key', $car_view_key->key);
            }
        }

        $car_view = CarsView::find()->where(['key_id' => $car_view_key->id, 'car_id' => $car->id])->one();
        if (!$car_view) {
            $car_view = new CarsView();
            $car_view->key_id = $car_view_key->id;
            $car_view->car_id = $car->id;
            $car_view->save();
        }

        return CarsView::find()->where(['car_id' => $car->id])->count();
    }


    private static function generateRandomString($length = 10)
    {
        $characters = '0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ';
        $charactersLength = strlen($characters);
        $randomString = '';
        for ($i = 0; $i < $length; $i++) {
            $randomString .= $characters[rand(0, $charactersLength - 1)];
        }
        return $randomString;
    }


    public function afterSave($insert, $changedAttributes)
    {
        $props = CarsProps::find()->where(['car_id'=>$this->car_id])->one();
        if(!$props){
            $props = new CarsProps();
            $props->car_id = $this->car_id;
        }



        $co = CarsView::find()->where(['car_id'=>$this->car_id])->count();
        $props->views = $co;
        $props->save();



        return parent::afterSave($insert, $changedAttributes); // TODO: Change the autogenerated stub
    }
}

controllers/CarsController.php
<?php

namespace app\controllers;

use app\models\Cars;
use app\models\CarsSearch;
use app\models\CarsSphinx;
use app\models\NewCarsBrands;
use app\models\NewCarsPackage;
use app\models\NewCarsPackageLib;
use app\widgets\Alert;
use phpDocumentor\Reflection\DocBlock\Tags\Var_;
use Yii;
use yii\filters\AccessControl;
use yii\data\ActiveDataProvider;
use app\models\Alerts;
use yii\helpers\ArrayHelper;

class CarsController extends BaseAdmin
{

    /**
     * {@inheritdoc}
     */
/*
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['index', 'add', 'del', 'view', 'alerts'],
                'rules' => [
                    [
                        'actions' => ['index', 'view', 'alerts'],
                        'allow' => true,
                        'roles' => ['carsView'],
                    ], [
                        'actions' => ['del', 'add'],
                        'allow' => true,
                        'roles' => ['carsAdd'],
                    ]
                ],
            ],
        ];
    }
*/
    public function actionIndex()
    {
        $searchModel = new CarsSearch();

        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);


        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    public function actionView($id)
    {
        $dataProvider = new ActiveDataProvider([
            'query' => Alerts::find()->where(['is', 'deleted', null])->orWhere(['deleted' => 0])->andWhere(['car_id' => $id]),
            'pagination' => [
                'pageSize' => 20,
            ],
        ]);
        $car = Cars::findOne($id);
        return $this->render('view', ['car' => $car, 'dataProvider' => $dataProvider]);
    }

    public function actionAlerts()
    {
        $alerts = Alerts::find()->groupBy('car_id')->all();


        $dataProvider = new ActiveDataProvider([
            'query' => Cars::find()->where(['id' => ArrayHelper::getColumn($alerts, 'car_id')]),
            'pagination' => [
                'pageSize' => 20,
            ],
        ]);
        return $this->render('alerts', ['dataProvider' => $dataProvider]);
    }

    public function actionAdd($id = 0)
    {
        $cars = new Cars();
        return $this->render('add', ['cars' => $cars]);
    }

    public function actionDel($id)
    {
        $car = Cars::findOne($id);

        if ($car) {
            $car->deleted = 1;
            $car->deleted_at = time();
            $car->save();
        }
        return $this->redirect("/cars");
    }


    public function actionTest($id = 0)
    {
        echo '<pre>';

        die;
    }

    public function actionUpdateParser($id){
        echo $id;
        echo '<pre>';
        echo exec("cd ../parse && node update_cars.js ".$id);
//        print_r(scandir("../parse"));
    }

}

views/cars/add.php
<?php
$this->title = 'Add Cars';

use app\components\Panel;
use yii\bootstrap\ActiveForm;
use \yii\helpers\ArrayHelper;
?>

<div>
    <div class="h">
        <h1>Add new Car</h1>
    </div>


    <?php $form = ActiveForm::begin([
        'layout' => 'horizontal',
        'fieldConfig' => [
            'horizontalCssClasses' => [
                'label' => 'col-sm-3',
                'offset' => 'col-sm-offset-3',
                'wrapper' => 'col-sm-9',
            ],
        ],
    ]); ?>
    <div class="col-xs-12 col-md-4">
        <?php Panel::begin(); ?>
        <?= $form->field($cars, 'ext_modframleidandiid')->dropDownList(ArrayHelper::map(\app\models\Framleidendur::find()->groupBy('id')->all(),'id','company')); ?>
        <?= $form->field($cars, 'flokkur')->dropDownList(ArrayHelper::map(\app\models\Flokkar::find()->all(),'id','name'));; ?>
        <?= $form->field($cars, 'litur')->dropDownList(ArrayHelper::map(\app\models\Litir::find()->all(),'id','name')); ?>
        <?= $form->field($cars, 'drif'); ?>
        <?= $form->field($cars, 'eldsneyti')
            ->dropDownList(ArrayHelper::map(\app\models\Eldsneyti::find()->all(),'id','name'));; ?>
        <?php Panel::end(); ?>
    </div>

    <div class="col-xs-12 col-md-4">
        <?php Panel::begin(); ?>

        <?php Panel::end(); ?>
    </div>

    <div class="col-xs-12 col-md-4">
        <?php Panel::begin(); ?>

        <?php Panel::end(); ?>
    </div>
    <?php ActiveForm::end(); ?>
</div>

views/cars/alerts.php
<?php
$this->title = 'Cars Alerts';

use yii\grid\GridView;
use app\components\Panel;
use yii\widgets\Pjax;
?>




<div class="row">
    <div class="col-md-12">

        <?php
        $name = 'cars_list';
        Panel::begin([
            'title' => $this->title,
//    'buttons' => [['title' => 'Add New', 'link' => '/companies/add']],
            'table_name' => $name
        ]);
        ?>
        <?php
        $column = [
            [
                'attribute'=>'api_id',
                'format' => 'raw',
                'value' => function ($d) {
                    return \yii\helpers\Html::a($d->api_id, '/cars/' . $d->id, ['data-pjax' => 0]);
                }
            ],
            'ext_modframleidandi',
            'extModframleidandi.models',
            [
                'attribute'=>'verd',
                'value' => function ($d) {
                    return number_format($d->verd * 1000) . " kr";
                }
            ], [
                'header' => 'Discount Price',
                'value' => function ($d) {
                    return number_format($d->verd * 1000) . " kr";
                }
            ], [
                'header' => 'On website Since',
                'value' => function ($d) {
                    $dStart = new DateTime($d->created);
                    $dEnd = new DateTime();
                    $dDiff = $dStart->diff($dEnd);
                    return $dDiff->days . " days";
                }
            ], [
                'header' => 'In search',
                'value' => function ($d) {

                }
            ], [
                'header' => 'Page views',
                'value' => function ($d) {

                }
            ], [
                'header' => 'Contact clicks',
                'value' => function ($d) {

                }
            ], [
                'header' => 'Alerts',
                'value' => function ($d) {

                }
            ], [
                'contentOptions' => ['class' => 'm-datatable__cell table-action-cell'],
                'header' => 'Action',
                'format' => 'raw',
                'value' => function ($d) {
                    return $this->render('/base/action', ['model' => $d, 'action' => 'cars']);
                }
            ]
        ];

        Pjax::begin([
            'id'=>'car-pjax'
        ]);
        echo GridView::widget([
            'id' => $name,
            'dataProvider' => $dataProvider,
//            'filterModel' => $searchModel,
            'columns' => $column,
        ]);

        Pjax::end();
        ?>
        <?php Panel::end(); ?>
    </div>
</div>

views/cars/view.php
<?php

use app\components\Panel;
use yii\helpers\Html;
use yii\widgets\Pjax;
use yii\grid\GridView;

$this->title = 'Car';
?>


<div class="row">
    <div class="col-sm-6">
        <?php Panel::begin(); ?>
        <div class="row">
            <div class="col-xs-7">
                <?php
                if (count($car->carsPhotos)) {
                    $url = 'https://bilasolur.is/CarImage.aspx?s=' . $car->company->api_id . '&c=' . $car->api_id . '&p=' . $car->carsPhotos[0]->photo_id . '&w=300';
                    echo Html::img($url, ['style' => 'width:100%;']);
                }
                ?>


            </div>
            <div class="col-xs-5">
                <h5><?= $car->title; ?></h5>
                <div>Verð <?= number_format($car->verd * 1000); ?></div>
                <div>Nýskráning <strong><?= $car->dyr; ?>/<?= $car->argerd; ?></strong></div>
                <div><strong><?= $car->eldsneyti0->name; ?></strong></div>
                <div>Akstur <strong><?= number_format($car->ekinn * 1000); ?> km</strong></div>
                <div>Næsta skoðun <?= $car->naestaskodun; ?></div>
                <div><?= $car->girartegund0->name; ?></div>
                <div>Litur <?= $car->litur0->name; ?></div>
                <hr/>

                <div style="font-size: 18px; font-weight: 400;">Verd <span
                            style="color: #5867dd; font-weight: bold;"><?= number_format($car->verd * 1000, null, null, '.'); ?> kr.</span>
                </div>


                <?php if ($car->aukahlutirath): ?>
                    <div><?= $car->aukahlutirath; ?></div>
                <?php endif; ?>

                <?php if ($car->skiptiodyrari): ?>
                    <div>Seljandi skoðar skipti á ódýrara</div>
                <?php endif; ?>

                <?php if ($car->skiptidyrari): ?>
                    <div>Seljandi skoðar skipti á dýrara</div>
                <?php endif; ?>

            </div>
        </div>


        <div class="row">
            <div class="col-xs-7">
                <div class="row">
                    <div class="col-xs-6">
                        <div>Skráð á söluskrá</div>
                        <div><strong><?= date("d.m.Y", strtotime($car->skrdags)); ?></strong></div>
                    </div>
                    <div class="col-xs-6">
                        <div>Síðast uppfært</div>
                        <div><strong><?= date("d.m.Y", strtotime($car->lastupdated)); ?></strong></div>
                    </div>
                </div>
                <div>Car status</div>
                <div>
                    <strong>
                        <?= $car->deleted == 0 ? 'Online' : 'offline'; ?>
                    </strong>
                </div>
            </div>
            <div class="col-xs-5">
                <?php if (!$car->deleted): ?>
                    <?php if ($car->company->api_id == 19): ?>
                        <b>Bi</b>
                        <a href="https://bilasolur.is/CarDetails.aspx?bid=<?= $car->company->api_id; ?>&cid=<?= $car->api_id; ?>&sid=<?= $car->ext_statid; ?>"
                           target="_blank"
                           class="btn m-btn--pill m-btn--air btn-accent m-btn m-btn--custom m-btn-sm m-btn--bolder">View
                            car
                            in browser</a>
                    <?php else: ?>
                        <a href="https://bilasolur.is/<?= $car->carsProps->url_bilasolur; ?>"
                           target="_blank"
                           class="btn m-btn--pill m-btn--air btn-accent m-btn m-btn--custom m-btn-sm m-btn--bolder">View
                            car
                            in browser</a>
                        <?= Html::a("Update Parser", ['/cars/update-parser', 'id' => $car->id]); ?>
                    <?php endif; ?>

                <?php endif; ?>
            </div>
        </div>
        <?php Panel::end(); ?>
    </div>
    <div class="col-sm-6">
        <div class="row">
            <div class="col-sm-6">
                <?php Panel::begin(); ?>
                graph 1
                <?php Panel::end(); ?>
            </div>
            <div class="col-sm-6">
                <?php Panel::begin(); ?>
                graph 2
                <?php Panel::end(); ?>
            </div>
        </div>
        <div class="row">
            <div class="col-sm-6">
                <?php Panel::begin(); ?>
                graph 3
                <?php Panel::end(); ?>
            </div>
            <div class="col-sm-6">
                <?php Panel::begin(); ?>
                graph 4
                <?php Panel::end(); ?>
            </div>
        </div>

    </div>
</div>

<div class="row">
    <div class="col-sm-8">
        <?php Panel::begin(['title' => 'Active alerts']); ?>

        <?php
        $name = 'alerts_list';
        $column = [
            'id',
            'email',
            'method',
            [
                'header' => 'Activated',
                'value' => function ($d) {
                    $dStart = new DateTime($d->created);
                    $dEnd = new DateTime();
                    $dDiff = $dStart->diff($dEnd);
                    return $dDiff->days . " days";
                }
            ],
            [
                'header' => 'Lasr send',
                'value' => function ($d) {
                    $al = app\models\AlertsLog::find()->where(['alert_id' => $d->id])->orderBy(['id' => SORT_DESC])->one();
                    if ($al) {
                        return $al->created;
                    }
                }
            ],
            [
                'header' => 'Total send',
                'value' => function ($d) {
                    return count($d->alertsLogs);
                }
            ], [
                'contentOptions' => ['class' => 'm-datatable__cell'],
                'header' => 'Action',
                'format' => 'raw',
                'value' => function ($d) {
                    return $this->render('/base/action', ['model' => $d, 'action' => 'alerts']);
                }
            ]
        ];


        Pjax::begin();
        echo GridView::widget([
            'id' => $name,
            'dataProvider' => $dataProvider,
            'columns' => $column,
        ]);
        Pjax::end();
        ?>
        <?php Panel::end(); ?>
    </div>
    <div class="col-sm-4">
        <?php Panel::begin(['title' => 'Audit Log']); ?>
        c
        <?php Panel::end(); ?>
    </div>
</div>